image: gitpod/workspace-mysql

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: dependencies and database
    init: |
      npm install
      gp await-port 3306
      npm run create_database
      npm run create_tables
  - name: dev server
    command: |
      gp await-port 3306
      npm run dev

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-browser
  - port: 3306
    onOpen: ignore
