GET http://localhost:3000/students
Content-Type: application/json

###

POST http://localhost:3000/students
Content-Type: application/json

{
    "firstName": "Hatim",
    "lastName": "Naimi"
}

###

GET http://localhost:3000/students/2
Content-Type: application/json

###

GET http://localhost:3000/students/2/classes
Content-Type: application/json

###

DELETE http://localhost:3000/students/2
Content-Type: application/json
